[project]
name = "ble-emulator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
   "bumble==0.0.212",
   "uvicorn==0.35.0",
   "fastapi==0.115.14"
]
